"use client"; 

import './globals.css'
import { Provider } from 'react-redux'
import store from '../app/utils/store';
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
//   icons: [], // Removes the default icon
// };

export default function RootLayout({ children }) {
  console.log("inside root ")
  return (
    <html lang="en">
      <body>
      <Provider store={store}>
      {children}
      </Provider>
      </body>
    </html>
  );
}